### PR TITLE
Add option to show/hide error messages

### PR DESCRIPTION
**Pull request by andi34**
Fix https://github.com/andreknieriem/photobooth/issues/160

### Option in admin panel
Screenshot_2019-10-25_07-39-11

### disabled error messages
Screenshot_2019-10-25_07-39-27

### enabled error messages
Screenshot_2019-10-25_07-39-49

### CODE REVIEW

**Comment by andi34** [comment]
I'll add proper strings/translations of we decide to add it, else i am not going to spend to much time with it (out of time today anyway)

**Comment by mhellmeier** [comment]
_Discussion about this implementation can be found in the related issue #160._

**Comment by andi34** [comment]
I'll force update tomorrow and remove the error message option in admin panel/config and only add the possibility to show or hide them.

**Comment by sualko** [comment]
I changed the default behavior, so that error messages are shown by default and people who start with this project have a helpful error message without configuring anything.

**Pull request merged**
