### PR TITLE
[WIP] Do not alter pictures unless filters applied

### PR DESCRIPTION
**Pull request by rawbertp**
This is a follow-up to #172 

@sualko

> I think we can also skip the jpeg conversion, if no filters/borders and so on are applied. That would also enhance the performance.

https://github.com/andreknieriem/photobooth/issues/172#issuecomment-549751955

Change:

When no filters selected the original image will be kept/used.

### CODE REVIEW

**Comment by sualko** [comment]
I think this pr needs an update because the commit can't be found.

**Comment by rawbertp** [comment]
Not sure what you mean? I can see 80a3daa76b1db6d77d088ec14af2469a81136ac2 even when not logged in...

**Comment by sualko** [comment]
I probably followed a link in an email and while you force-pushed the referenced commit was not there. Sorry for the confusion.

**Comment by andi34** [comment]
https://github.com/andreknieriem/photobooth/pull/226 was merged.

When no filters selected the original image will be kept/used: https://github.com/andreknieriem/photobooth/pull/226/commits/e3678a710470dd0204ac26101419cefcadb69bac

**Pull request closed without merging**
