### PR TITLE
Optimize performance

### LINKED ISSUE #117: Question on Performance
Hi, 
i am using photobooth for a while, first on a pi zero and now on a pi model 3B+.
If I use the plain git version it takes approximately between 8 and 11 seconds even on the 3B+ to show the picture in browser after the picture was taken by camera.

This is a bit long in my oppinion. 
How long does it take with your installation? 
Do i need to do some environment changes to my pi?

My current solution to solve this is 
- to totally disable gallery and image processing when gallery is not used (no thumbnail creation and no image changes), 
- to disable qr code creation and to turn of qr code creation when qr is disabled and 
- to set the picture quality to produce approximately 3 MB pictures. 

This leads to a processing time of 5 to 7 seconds.
My configuration is a Pi Model 3B+, with a Canon ES 600d camera.
Raspbian Buster
Gphoto: gphoto2 2.5.23, libgphoto2 2.5.23

### PR DESCRIPTION
**Pull request by sualko**
- [x] separate trigger and post-process task
- [x] if possible use faster method to resize a picture
- [x] remove time measurement which was used for development

fix #117

### CODE REVIEW

**Comment by sualko** [comment]
@RaphaelKunis can you test this pull request?
@Norman-Sch can you also test this pull request, because I think it will also solve your issue.

Please don't forget to run `yarn build` after you did `git fetch origin && git checkout origin/feature/performance` and a force reload (ctrl+F5).

**Comment by sualko** [comment]
@andi34 please don't merge this, because I would like to release a bug fix version before.

**Comment by andi34** [comment]
@sualko don't worry, i`ll give the merge to your hands.
https://github.com/andreknieriem/photobooth/pull/142 would not be needed as the modified parts are removed here. you would have to revert my commit again to not have any merge conflicts.

**Comment by RaphaelKunis** [comment]
Just tested it on my raspberry with canon camera. 
It seems to work good.
I made more than 30 shots with different filters and one collage. 
It now takes around 5 to 6 seconds to display the picture after taking it on the camera. 
This is very good.
The filters are applied later, what is ok for me.
What is a bit strange is that the "Cheeeeese" is displayed half the time till displaying the final photo. Thereby the label "Processing" is displayed too late in my opinion.
On time i had a "internal server error on applyEffects.js" due to a timeout. This was maybe a memory problem. I do not know and i could not reproduce it.

Thanks for the effort.

**Comment by andi34** [comment]
@RaphaelKunis you can adjust the cheese time in admin panel

**Comment by sualko** [comment]
> What is a bit strange is that the "Cheeeeese" is displayed half the time till displaying the final photo.

You mean the "Cheeeeese" message is still displayed after the picture was taken? There is no perfect solution for this, because we can't guess when the picture was taken. 5 seconds sounds still a bit slow. For me it's below 2 seconds for a 15MP picture on a Raspberry Pi 3. Maybe you have to lower your resolution.

> On time i had a "internal server error on applyEffects.js" due to a timeout.

Depends on your hardware and webserver configuration and is not directly related to photobooth.

**Comment by RaphaelKunis** [comment]
I already tried to lower the resolution. It helped a little.
Just found out that the five second waiting time is spent in gphoto2.
There seems to be a problem when using capture-image-and-download
Changed the command to "--trigger-capture"
"gphoto2 --trigger-capture; gphoto2 -P --filename=%s --new --force-overwrite"
Now it also takes less than two seconds.

**Pull request merged**
