### PR TITLE
fix start screen layout

### LINKED ISSUE #84: Bug v1.9.0: fonts size needs adjustment
Hi,

Is it possible to adjust the Fonts size ?

IMG_0639

### PR DESCRIPTION
**Pull request by sualko**
fix #84

### CODE REVIEW

**Comment by andi34** [comment]
@thymon13 tested?

```
git fetch https://github.com/sualko/photobooth fix/start-layout
git cherry-pick 4dcbe2ece0686a13894ef1ff18cc6b86c4082bd3
```

So you don't need to add it by hand or pull the files.

**Comment by thymon13** [comment]
@andi34 Yes nice !

Works fine for the start screen layout.
But not for the QR Code after take a picture.

IMG_0657

**Comment by andi34** [comment]
@thymon13 font size looks ok for the size of QR code.
We can merge the PR for the Startscreen layout if @sualko likes to put the QR code size to a different PR.

**Comment by andi34** [comment]
@sualko you'd like to take a look at the Oversized QR in this PR too?

**Comment by sualko** [comment]
> Works fine for the start screen layout.

Therefore I merged this pr. I will add a fix for the qr code oversize after the refactoring changes are merged, because otherwise there are to many conflicts.

**Pull request merged**
