### PR TITLE
General changes

### PR DESCRIPTION
**Pull request by andi34**
- pack-build: add button.py & README
- Collage: allow to abort Collage creation if we take collage **with** interruption (Fix https://github.com/andreknieriem/photobooth/issues/163 )
- Collage: use "Next Picture" instead "New Picture"
- install-raspbian.sh: 
  - ask before deleting `hmtl` folder (cherry-picked and adjusted from https://github.com/andreknieriem/photobooth/pull/162 )
  - make kiosk mode optional

### CODE REVIEW

**Comment by andi34** [comment]
We can add other commits without a direct issue here too and adjust the title of this PR

**Comment by andi34** [comment]
Screenshot_20191110-132935

**Comment by andi34** [comment]
Overseen there was an issue for collage cancel https://github.com/andreknieriem/photobooth/issues/163

**Comment by sualko** [comment]
Ready to merge?

**Comment by sualko** [comment]
Can you include `fix #163` in the related commit message? Because than the issue is automatically closed and you can easily see why the issue was closed.

**Comment by andi34** [comment]
Sure, I'll do later

**Comment by andi34** [comment]
I'll also add https://github.com/andi34/photobooth/commit/366ea6661cd83c7087b810508974ddccf972e122 as it wasn't in the Download Button PR

**Pull request merged**
