### PR TITLE
merge default and custom config deeply

### LINKED ISSUE #130: Problem mit Hochzeitssymbol
Ich habe seit gestern ein Problem welches ich heute bei einem frisch aufgesetzten System immer noch nachvollziehen kann.
Ich kann das Symbol für Hochzeiten nur auswählen und dauerhaft speichern wenn keine Namen eingetragen sind. Sobald ich einen Namen eintrage und speichere steht dort wieder Symbol wählen. Einzige Änderung zum Standart ist das Livewallpaper. Kann das jemand bestätigen

### PR DESCRIPTION
**Pull request by sualko**
fix #130
obsoletes #131

### CODE REVIEW

**Comment by sualko** [comment]
@obkram can you test this pull request, so that we can release a bug fix version? If you cloned this repository, use the following commands:

```
git fetch origin
git checkout origin/fix/config
```

**Comment by obkram** [comment]
Do I have to use the command in an especially folder? /var/www/html/...

**Comment by sualko** [comment]
> Do I have to use the command in an especially folder?

Yes, in the root folder of your photobooth installation. The installation guide uses `var/www/html/`.

**Comment by obkram** [comment]
It’s working very well. The problem seems to be fixed. Thank you

**Comment by sualko** [comment]
> It’s working very well. The problem seems to be fixed. Thank you

Thanks for testing. :+1:

**Pull request merged**
