### PR TITLE
Various updates 

### LINKED ISSUE #11: Fotos lassen sich nicht öffnen.
Hallo.
Ich bin jetzt schon mehrere Monate immer wieder damit beschäftigt aber ich kann die Bilder in der Gallery einfach nicht über mein Ipad öffnen. Ich kann die Thumbs sehen aber beim antippen der Bilder friert die komplette Seite ein. nichts lässt sich mehr drücken. Das gleiche habe ich bei meinem Oneplus One auch. Bei einem Iphone 6 oder 7 tritt der selbe Effekt auf. Die Seite friert ein. Leider auch bei einem neueren Ipad auf das ich zurückgreifen könnte und bei einem Android Tablett ebenfalls. Bild angetippt und nichts passiert mehr. Die Seite muss neu geladen werden.
Nach mehreren Versuchen von der Homepage ein paar Tipps abzugreifen und z.B. die Auflösung runterzuschrauben hab ich aufgegeben.
Grad nochmal dran gesetzt und das Update mal installiert. leider das gleiche Spiel beim Ipad.
Ich bin ratlos. Wenn ich Bilder von der Herstellerseite der Gallerie öffne läuft alles PErfekt.
Nur hier schein irgendwo der Wurm drinn zu sein.
MfG John

### PR DESCRIPTION
**Pull request by andi34**
- added  #54 and updated formatting
- Parts of #24 are included:
  - It should fix #11, and #2
  - Added the ability to show the date/time in the caption of the images in the gallery, which is possible to enable or change in the settings.
- Added goodies from other forks:
  - disable gallery via config
  - set countdown timer via config
  - set cheeeese! Timer via config (https://github.com/andreknieriem/photobooth/pull/52  but updated as proper commit and without changes on default setup).
  - enable scrollbar in gallery via config
  - added empty gallery message
- Added all config options to admin panel, including translations.
- Made start screen message (title and subtitle) an config option which can be changed via admin panel too
- Some readme updates
- More french translation
- Some other small Bugfixes and improvements.

### CODE REVIEW

**Comment by andi34** [comment]
Screenshot_20190613-185924
Screenshot_20190613-185937

Mail option will be a seperated PR.

**Comment by Norman-Sch** [comment]
Wow, awesome work!!!

could you please check following issue:
https://github.com/andreknieriem/photobooth/issues/41 # #

**Comment by andi34** [comment]
One typo... general_date_format... will fix asap. After that good to go my side, finally. 😀👍

**Comment by andi34** [comment]
Finally done and i am quite happy with the result.

If something should still be adjusted let me know (e.g. in README photobooth vs photobooth+? add back link to your github project in the headline?) and i'll update before you merge.

next thing which needs to be looked at: add dowload button. i don't know many people using QR...
you've looked at that in the past?

**Comment by andi34** [comment]
Found one thing, even if it won't hurt as it depends on $config['file_format_date']:

config['show_date'] = true; --> should be false by default.

Will update the commit which turned it on by accident once I get feedback if something else needs adjustment.

**Comment by andi34** [comment]
Screenshot_20190614-163400
Screenshot_20190614-163412


Own PR later:
Screenshot_20190614-163428

**Comment by andi34** [comment]
@andreknieriem LivePreview works using the camera or webcam?
If webcam I need to adjust the README update once again. Somehow thought it was using gphoto2 for it but looks different code side.

**Comment by andi34** [comment]
Also added https://github.com/andreknieriem/photobooth/pull/54

Added empty gallery message and made it configurable via admin page

**Comment by andi34** [comment]
- Made start screen message (title and subtitle) an config option which can be changed via admin panel too.
- no need to make empty gallery message an config/admin option, switched to language lables instead
- updated install instructions for Raspbian Buster (thx to @tobiashaas)

**Comment by dnks23** [comment]
when will this be merged? any thing still to do?

**Comment by andi34** [comment]
Can push one more commit which is good to go tomorrow evening.

After that we need to wait for André to press the submit button.

**Comment by andreknieriem** [comment]
Alles klar. Dann warte ich noch. Ich habe durch Familiennachwuchs wenig Zeit. Ich merge es aber gerne bald rein ;)

**Comment by andi34** [comment]
Super, herzlichen Dank. Privat geht hier auch alles drunter und drüber. Werde das aber heute Abend pushen dann können wir hier ran einen Haken machen :)

**Comment by andi34** [comment]
Good to go

**Comment by andi34** [comment]
Screenshot_20190629-233038

**Comment by andi34** [comment]
Danke :) 👍

**Pull request merged**
