### PR TITLE
Add greek language

### LINKED ISSUE #122: Neue Sprache (Griechisch)
Hallo Leute,
weiß nicht ob es hier an der Richtigen stelle gepostet ist. Darum löschen wenn Falsch.

Hier eine neue Sprache für das Photobooth.
Mein Griechisch ist nicht Perfekt daher mit einem Online Übersetzer gemacht. Bitte ändern wenn was falsch ist.

[Griechisch](https://github.com/fossil74/Photobooth/blob/master/resources/lang/gr.js)

### PR DESCRIPTION
**Pull request by andi34**
close #122

### CODE REVIEW

**Comment by andi34** [comment]
fixed a typo, sry for the force-push

**Comment by andi34** [comment]
@sualko stupid question: if a string does not exist fall back to English translation on that string? Possible to implement?

**Comment by sualko** [comment]
>  if a string does not exist fall back to English translation on that string?

Currently this is not the case.

> Possible to implement?

Sure.

We should maybe also move the email template translation to the language file, transfer it to json, so that it is readable by php.

**Comment by andi34** [comment]
> We should maybe also move the email template translation to the language file, transfer it to json, so that it is readable by php.

I'd keep it an option in admin menu, if it can be handled with that we can move it to the language file.

**Pull request merged**
