### PR TITLE
Live View as background

### PR DESCRIPTION
**Pull request by Seilafeh**
motion is required!

sudo apt-get install motion

Webcam is required and /etc/motion/motion.conf needs to be changed to your needs. e.g. starting on boot, using videoX, resolution etc.

ToDo:
change countdown blur into softer blur.

### CODE REVIEW

**Comment by andreknieriem** [comment]
Very interesting. Will test this and merge a version if this! Thanks

**Comment by c-weidinger** [comment]
Seilafeh, have you got it working?? I installed Motion and added your style.css changes, but it shows nothing?

**Comment by obkram** [comment]
Funktioniert bei mir seit einem Jahr wunderbar. Ich habe in der Box einen zweiten RPI eingebaut auf welchem MotioneyeOS läuft.
Wenn man das so nutzen möchte muss man nur die Streamingadresse von localhost auf die Streamingadresse ( IP und Port ) der am Motioneye angeschlossenen USB Kamera angeben. Dann geht es. Motioneye muss dann auf ein gemeinsam genutztes Wlan oder optional den Hotspot des RPI mit Photobooth+ verbunden werden.

**Comment by abacaxi3000** [comment]
> 
> 
> motion is required!
> 
> sudo apt-get install motion
> 
> Webcam is required and /etc/motion/motion.conf needs to be changed to your needs. e.g. starting on boot, using videoX, resolution etc.
> 
> ToDo:
> change countdown blur into softer blur.

Thanks for the Idea, Seilafeh. I installed everything and the Live View works finde. There are just two issues: The bigger one is, that the gallery-button seems to be broken. I can't go to the gallery. Could you test it maybe? I just copied the lines from your style.css

And do you think it might be possible to have a permament Live View?

**Comment by andi34** [comment]
Added to FAQ: https://github.com/andreknieriem/photobooth/issues/69

**Pull request closed without merging**
