### PR TITLE
Various updates

### PR DESCRIPTION
**Pull request by andi34**
Parts of https://github.com/andreknieriem/photobooth/pull/24 are included.
Added some goodies from other forks.
Some readme updates.

### CODE REVIEW

**Comment by andi34** [comment]
Thing to do: Countdown timer option and enable/disable gallery needs to be added to admin panel

**Comment by andi34** [comment]
I'll work on the README again tomorrow. Please don't merge before.

**Comment by andi34** [comment]
https://github.com/andi34/photobooth/commit/fb579758bbfd05fd4314b705dc8271acfc75393b

https://github.com/andi34/photobooth/commit/91886de83a3a94e73d5173fa47fab01e1f14bc36

Config changes for admin panel. Can be tested once admin Page works again.

**Comment by andi34** [comment]
Sorry fuer die vielen updates. Denke jetzt passt alles.
Rest dann gerne per anderer Pull Request sobald das gemerged ist :)

**Comment by andi34** [comment]
Achso, ich könnte noch die englischen und französischen Übersetzungen die Tage hinzufügen.

Gewünscht?

**Comment by andreknieriem** [comment]
Gerne!

**Comment by andi34** [comment]
Ein Freund aus Paris uebersetzt die Tage was im fr.js noch auf englisch ist. Werde https://github.com/andreknieriem/photobooth/pull/48/commits/aeb69d6e881dd32483188766798a558c86fab3e1 dann entsprechend updaten.

Sage bescheid wenns ready ist :)

**Comment by andi34** [comment]
Done. Translations added to the existing commits. Also missing french translation added.

I've also (by accident added) https://github.com/andreknieriem/photobooth/pull/52 but with cleaner commits. Keep in here?

**Comment by andi34** [comment]
I found a solution for https://github.com/andreknieriem/photobooth/issues/49 , will have to update this here later. Don not merge before.

**Comment by andi34** [comment]
Should be ok now, also admin page

**Comment by andi34** [comment]
Mh... Unable to reopen, lol

**Pull request closed without merging**
