### PR TITLE
use relative paths

### PR DESCRIPTION
**Pull request by sualko**
this allows to install photobooth in a subfolder

### CODE REVIEW

**Comment by andi34** [comment]
https://github.com/andreknieriem/photobooth/issues/23

**Comment by andi34** [comment]
Mentioned 2 lines need to be updated too?

**Comment by sualko** [comment]
I think you accidentally merged this pr. You find the squashed commit here 7d1030bf550ee468f16196fc63ad521666c069d1

**Comment by andi34** [comment]
Fixed it already :)

**Pull request merged**
