### PR TITLE
admin: delay reload after save/reset

### LINKED ISSUE #109: v2.0.0: Add delay to reload the admin page after clicking "save"
In some cases it seems to take a moment to have settings saved on Raspberry Pi

### PR DESCRIPTION
**Pull request by andi34**
fix #109

### CODE REVIEW

**Comment by msmedien** [comment]
@andi34 Works now. Thank you. :)

**Comment by andi34** [comment]
@sualko ok this way or you've a better idea?

**Comment by sualko** [comment]
This doesn't make sense at all. If the success handler is called, all settings should be saved. So we should find the root case of the issue. Can you try it with the dev console open and disabled cache? Maybe it's a caching issue. In general we should remove the reload, because it a bad user experience if the page reloads without indication. I think applying the ui changes directly would be sufficient.

**Comment by andi34** [comment]
you mean disabled cache in network panel?

Screenshot_2019-10-10_17-46-59

**Comment by sualko** [comment]
> you mean disabled cache in network panel?

jup

**Comment by sualko** [comment]
Ok, at least I'm able to reproduce it. So I'm probably able to fix it :-)

**Comment by sualko** [comment]
Can you check if you have opcache enabled? Just open the phpinfo.php and look for the opcache entry.
2019-10-10 18 13 54 localhost ade8336c0d1b

If you had created a new branch in this repo, I could fix it by myself :wink: 

```
diff --git a/api/admin.php b/api/admin.php
index b8fd906..311e7c9 100644
--- a/api/admin.php
+++ b/api/admin.php
@@ -65,6 +65,8 @@ if ($data['type'] == 'config') {
     $content = "<?php\n\$config = ". var_export(arrayRecursiveDiff($newConfig, $defaultConfig), true) . ";";
 
     if (file_put_contents($file, $content)) {
+        clearCache($file);^M
+^M
         echo json_encode('success');
     } else {
         echo json_encode('error');
@@ -93,3 +95,11 @@ function arrayRecursiveDiff($aArray1, $aArray2)
     }
     return $aReturn;
 }
+^M
+function clearCache($file) {^M
+    if (function_exists('opcache_invalidate') && strlen(ini_get("opcache.restrict_api")) < 1) {^M
+        opcache_invalidate($file, true);^M
+    } elseif (function_exists('apc_compile_file')) {^M
+        apc_compile_file($file);^M
+    }^M
+}^M
```

**Comment by andi34** [comment]
@sualko you should be able to push here directly too

**Comment by andi34** [comment]
I've given you access to my fork.
Can't test as my stepdaughter is on the TV right now ;)

**Pull request closed without merging**
