### PR TITLE
Make JPEG quality configurable

### PR DESCRIPTION
**Pull request by rawbertp**
Make jpeg image quality configurable.

Refers to #172

### CODE REVIEW

**Comment by andi34** [comment]
At the moment there's no fall-back to English as default language. Could you add translation for the other languages too? (Iused Google translate to have a basic text at least)

**Comment by rawbertp** [comment]
I added the missing translations but I'm not especially proud of them... ;)

**Comment by andi34** [comment]
I am also not that happy doing it this way always. We can skip those once we have a way to fall back to English if one is missing in a language file.
It's on the Todo list https://github.com/andreknieriem/photobooth/issues/125

**Comment by andi34** [comment]
works fine. thanks :)

**Comment by sualko** [comment]
Thanks for your contribution :+1:

**Pull request merged**
