### PR TITLE
Add possibility to set time for "Cheeeeeese!"

### PR DESCRIPTION
**Pull request by Norman-Sch**
control time for cheeeeese!
with my setup 1000ms is to short to take the picture.
"Processing" was already shown while the camera was released.

### CODE REVIEW

**Comment by andi34** [comment]
Please add to admin Page too.
Can you squash them into one commit only and give it proper commit name and description?

**Comment by andi34** [comment]
Default value should not be changed here.

**Comment by andi34** [comment]
https://github.com/andi34/photobooth/commit/74cefa340f275ce330d78212746a05dbfd13f70c

;)

**Comment by andreknieriem** [comment]
merged in 1.5.3

**Pull request closed without merging**
