### PR TITLE
Handle take photo error cases

### PR DESCRIPTION
**Pull request by sualko**

### CODE REVIEW

**Comment by andi34** [comment]
$source is only used here https://github.com/andreknieriem/photobooth/blob/3b8e41790bb76d3d2471f16d2ede2220d5e2f192/api/takePic.php#L355

and already destroyed here https://github.com/andreknieriem/photobooth/blob/3b8e41790bb76d3d2471f16d2ede2220d5e2f192/api/takePic.php#L358


Another thing:
we might want to destroy $new https://github.com/andreknieriem/photobooth/blob/3b8e41790bb76d3d2471f16d2ede2220d5e2f192/api/takePic.php#L56

**Comment by andi34** [comment]
We also might want to change https://github.com/andreknieriem/photobooth/blob/3b8e41790bb76d3d2471f16d2ede2220d5e2f192/api/takePic.php#L366

to 

```
    if ($imageResource) {
        imagedestroy($imageResource);
    }
```

**Comment by andi34** [comment]
https://github.com/andreknieriem/photobooth/blob/3b8e41790bb76d3d2471f16d2ede2220d5e2f192/api/takePic.php#L270

While on it:
Don't we only want to apply a filter if $_POST['filter'] is **not** empty and if it's not `imgPlain`?
There's a reason this has changed?
Shouldn't it be `if (!empty($_POST['filter']) && $_POST['filter'] !== 'imgPlain') {` ?

**Comment by andi34** [comment]
Another question:
Ca't we remove the empty check? We already check here if a filter is set/provided https://github.com/andreknieriem/photobooth/blob/3b8e41790bb76d3d2471f16d2ede2220d5e2f192/api/takePic.php#L256-L260

**Comment by sualko** [comment]
> We also might want to change imagedestroy($imageResource); 

I see no need for such a change. `$imageResource` is always set at that position.

> Don't we only want to apply a filter if $_POST['filter'] is not empty and if it's not imgPlain?

You are right. I did a mistake there.

> Can't we remove the empty check? We already check here if a filter is set/provided

No because `empty !== isset`. A variable can be set even if it is empty.

I will fix the filter issue and merge it afterwards. Thanks for your review.

**Pull request merged**
