### PR TITLE
add install script for raspbian

### PR DESCRIPTION
**Pull request by sualko**
This script transforms every Raspberry Pi in a Photobooth kiosk. This means browser is started on boot and everything is ready to go.

```
wget https://raw.githubusercontent.com/andreknieriem/photobooth/feature/install-script/install-raspbian.sh
sudo bash install-raspbian.sh
```

### CODE REVIEW

**Comment by andi34** [comment]
This should work on most parts also on Debian and Debian based distributions.
Set $IS_PIE = true and remove on Debian unused parts depending on it (kiosk mode).

 Disable camera automount should also be optional and asked for

**Comment by sualko** [comment]
> This should work on most parts also on Debian and Debian based distributions.

The important word is **should**. I don't want and also don't have the time to test the script on every blank system. Therefore this install script is only for Raspbian.

> Disable camera automount should also be optional and asked for

This script is intended for noobs and therefore I think the less options are better. One script, one purpose.

This is only my opinion. Feel free to change the script as you like.

**Comment by andi34** [comment]
> Better to write in the documentation "Check the camera function before removing the execution permission on gphoto2 Volume Monitor"
> 
> If i delete the gvfs or removing the execution permission, my camera dont take photos anymore. It's an old Sony alpha58. Maybe there are some other cameras with the same issue? Just as an thought...

Thats why we might think about asking instead

**Comment by sualko** [comment]
> Thats why we might think about asking instead

But which user knows that he should not disable this service? If the user knows this, than he will probably look at the script, or do it by hand.

**Comment by andi34** [comment]
If we add this script to setup the booth we should mention in Wiki too that some cameras might need it and tell how they can add back the execution permission.

**Pull request merged**
