### PR TITLE
update readme to reduce required permissions

### LINKED ISSUE #76: Enhancement: Fix giving to much permissions
The installation guide says

> Give sudo rights to the webserver user (www-data)

I know this application runs probably on an enclosed system, but I think given the webserver user root permissions is in general a bad idea. Just as [gphoto warns](http://www.gphoto.org/doc/manual/FAQ.html#FAQ-find-camera):

> AND DO NOT RUN gphoto2 AS ROOT. And no other libgphoto2 frontend either.

The better solution would be to [setup the correct permission](http://www.gphoto.org/doc/manual/permissions-usb.html) for your usb port. If I have time to test the configuration I will open a pull request to update the readme.

### PR DESCRIPTION
**Pull request by sualko**
fix #76

### CODE REVIEW

**Comment by andi34** [comment]
Looks good to me. Ready to merge?

**Comment by sualko** [comment]
I think so.

**Comment by andi34** [comment]
Ok, merge? I've seen you've have a similar patch (https://github.com/sualko/photobooth/commit/0d75ab446f73f5188871b2c60bbd798387b4d38d) in the refactor branch wich will conflict here (README) and needs to be solved on merge by hand.
In case refactoring is ready soon it's the question to merge it from there?

**Comment by sualko** [comment]
> Ok, merge?

If you gave it a try and everything is working, you can merge it.

> and needs to be solved on merge by hand

I know and will take care of it.

**Comment by andi34** [comment]
Was sure you tested. Takes about 10 days until I can test myself.

**Comment by andi34** [comment]
I've added the installation instructions to the wiki:
https://github.com/andreknieriem/photobooth/wiki

**Comment by andi34** [comment]
@tobiashaas @vdubuk @obkram could someone of you check the new instructions and confirm if it is working?
https://github.com/andreknieriem/photobooth/pull/86/files

**Comment by andi34** [comment]
`sudo -u www-data gphoto2 --capture-image` doesn't work for me, will play around later/tomorrow and see again.
Works as user pi.

**Comment by andi34** [comment]
```
pi@raspberrypi:/var/www $ ls -l /usr/local/lib/
insgesamt 584
drwxr-xr-x 3 root root    4096 Okt  7 19:20 libgphoto2
-rwxr-xr-x 1 root root    1040 Okt  7 19:20 libgphoto2.la
drwxr-xr-x 3 root root    4096 Okt  7 19:20 libgphoto2_port
-rwxr-xr-x 1 root root    1029 Okt  7 19:20 libgphoto2_port.la
lrwxrwxrwx 1 root root      25 Okt  7 19:20 libgphoto2_port.so -> libgphoto2_port.so.12.0.0
lrwxrwxrwx 1 root root      25 Okt  7 19:20 libgphoto2_port.so.12 -> libgphoto2_port.so.12.0.0
-rwxr-xr-x 1 root root  113756 Okt  7 19:20 libgphoto2_port.so.12.0.0
lrwxrwxrwx 1 root root      19 Okt  7 19:20 libgphoto2.so -> libgphoto2.so.6.1.0
lrwxrwxrwx 1 root root      19 Okt  7 19:20 libgphoto2.so.6 -> libgphoto2.so.6.1.0
-rwxr-xr-x 1 root root  445636 Okt  7 19:20 libgphoto2.so.6.1.0
drwxr-xr-x 2 root root    4096 Okt  7 19:20 pkgconfig
drwxr-xr-x 3 root root    4096 Sep 26 02:17 pypy2.7
drwxrwsr-x 4 root staff   4096 Sep 26 02:11 python2.7
drwxrwsr-x 3 root staff   4096 Sep 26 02:10 python3.7
drwxr-xr-x 2 root root    4096 Okt  7 19:20 udev
pi@raspberrypi:/var/www $ sudo -u www-data -s
www-data@raspberrypi:~$ ls /usr/local/
bin  etc  games  include  lib  man  sbin  share  src
www-data@raspberrypi:~$ ls -l /usr/local/lib/
insgesamt 584
drwxr-xr-x 3 root root    4096 Okt  7 19:20 libgphoto2
-rwxr-xr-x 1 root root    1040 Okt  7 19:20 libgphoto2.la
drwxr-xr-x 3 root root    4096 Okt  7 19:20 libgphoto2_port
-rwxr-xr-x 1 root root    1029 Okt  7 19:20 libgphoto2_port.la
lrwxrwxrwx 1 root root      25 Okt  7 19:20 libgphoto2_port.so -> libgphoto2_port.so.12.0.0
lrwxrwxrwx 1 root root      25 Okt  7 19:20 libgphoto2_port.so.12 -> libgphoto2_port.so.12.0.0
-rwxr-xr-x 1 root root  113756 Okt  7 19:20 libgphoto2_port.so.12.0.0
lrwxrwxrwx 1 root root      19 Okt  7 19:20 libgphoto2.so -> libgphoto2.so.6.1.0
lrwxrwxrwx 1 root root      19 Okt  7 19:20 libgphoto2.so.6 -> libgphoto2.so.6.1.0
-rwxr-xr-x 1 root root  445636 Okt  7 19:20 libgphoto2.so.6.1.0
drwxr-xr-x 2 root root    4096 Okt  7 19:20 pkgconfig
drwxr-xr-x 3 root root    4096 Sep 26 02:17 pypy2.7
drwxrwsr-x 4 root staff   4096 Sep 26 02:11 python2.7
drwxrwsr-x 3 root staff   4096 Sep 26 02:10 python3.7
drwxr-xr-x 2 root root    4096 Okt  7 19:20 udev
www-data@raspberrypi:~$ 
www-data@raspberrypi:~$ ls -l
insgesamt 4
drwxr-xr-x 2 www-data www-data 4096 Okt  7 19:13 html
www-data@raspberrypi:~$ gphoto2 --capture-image
                                                                               
*** Fehler ***      
An error occurred in the io-library ('I/O-Problem'): Keine Fehlerbeschreibung verfügbar.
FEHLER: Konnte Bild nicht aufnehmen.
FEHLER: Konnte nicht aufnehmen.

*** Fehler ***      
An error occurred in the io-library ('I/O-Problem'): Keine Fehlerbeschreibung verfügbar.
www-data@raspberrypi:~$ 
```

Any idea? `--capture-image` is not possible as www-data user.

**Comment by sualko** [comment]
Can the root user take a picture? Because the error message doesn't talk about permissions. The second think is that I read that depending on the version, udev has different formats. So please check other file inside `/etc/udev/rules.d/` if they look similar to my proposed file.

**Comment by andi34** [comment]
As user pi no issues to take a picture

**Comment by andi34** [comment]
```
pi@raspberrypi:/var/www/html $ cat /etc/udev/rules.d/90-libgphoto2.rules 
# udev rules file for libgphoto2 devices (for udev 201 version)
# Created from this library:
#   libgphoto2      2.5.22         all camlibs, gcc, ltdl, EXIF
#   libgphoto2_port 0.12.0         iolibs: disk ptpip serial usb1 usbdiskdirect usbscsi, gcc, ltdl, USB, serial without locking
#
# this file is autogenerated, local changes will be LOST on upgrades
ACTION!="add|bind", GOTO="libgphoto2_rules_end"
SUBSYSTEM!="usb", GOTO="libgphoto2_usb_end"
ENV{ID_USB_INTERFACES}=="", IMPORT{builtin}="usb_id"
ENV{ID_USB_INTERFACES}=="*:060101:*", ENV{ID_GPHOTO2}="1", ENV{GPHOTO2_DRIVER}="PTP", MODE="0660", GROUP="plugdev", GOTO="libgphoto2_usb_end"


LABEL="libgphoto2_usb_end"

KERNEL=="sg[0-9]*", ATTRS{idVendor}=="1908", ATTRS{idProduct}=="1315", ENV{ID_GPHOTO2}="1", ENV{GPHOTO2_DRIVER}="proprietary", MODE="0660", GROUP="plugdev"
KERNEL=="sg[0-9]*", ATTRS{idVendor}=="1908", ATTRS{idProduct}=="1320", ENV{ID_GPHOTO2}="1", ENV{GPHOTO2_DRIVER}="proprietary", MODE="0660", GROUP="plugdev"
KERNEL=="sg[0-9]*", ATTRS{idVendor}=="1908", ATTRS{idProduct}=="0102", ENV{ID_GPHOTO2}="1", ENV{GPHOTO2_DRIVER}="proprietary", MODE="0660", GROUP="plugdev"
KERNEL=="sg[0-9]*", ATTRS{idVendor}=="1908", ATTRS{idProduct}=="3335", ENV{ID_GPHOTO2}="1", ENV{GPHOTO2_DRIVER}="proprietary", MODE="0660", GROUP="plugdev"
KERNEL=="sg[0-9]*", ATTRS{idVendor}=="04b0", ATTRS{idProduct}=="0116", ENV{ID_GPHOTO2}="1", ENV{GPHOTO2_DRIVER}="proprietary", MODE="0660", GROUP="plugdev"
KERNEL=="sg[0-9]*", ATTRS{idVendor}=="04b0", ATTRS{idProduct}=="0108", ENV{ID_GPHOTO2}="1", ENV{GPHOTO2_DRIVER}="proprietary", MODE="0660", GROUP="plugdev"
KERNEL=="sg[0-9]*", ATTRS{idVendor}=="04b0", ATTRS{idProduct}=="0110", ENV{ID_GPHOTO2}="1", ENV{GPHOTO2_DRIVER}="proprietary", MODE="0660", GROUP="plugdev"
KERNEL=="sg[0-9]*", ATTRS{idVendor}=="04b0", ATTRS{idProduct}=="010e", ENV{ID_GPHOTO2}="1", ENV{GPHOTO2_DRIVER}="proprietary", MODE="0660", GROUP="plugdev"
KERNEL=="sg[0-9]*", ATTRS{idVendor}=="04b0", ATTRS{idProduct}=="0104", ENV{ID_GPHOTO2}="1", ENV{GPHOTO2_DRIVER}="proprietary", MODE="0660", GROUP="plugdev"
KERNEL=="sg[0-9]*", ATTRS{idVendor}=="04b0", ATTRS{idProduct}=="0401", ENV{ID_GPHOTO2}="1", ENV{GPHOTO2_DRIVER}="proprietary", MODE="0660", GROUP="plugdev"
KERNEL=="sg[0-9]*", ATTRS{idVendor}=="07b4", ATTRS{idProduct}=="0105", ENV{ID_GPHOTO2}="1", ENV{GPHOTO2_DRIVER}="proprietary", MODE="0660", GROUP="plugdev"
KERNEL=="sg[0-9]*", ATTRS{idVendor}=="07b4", ATTRS{idProduct}=="0105", ENV{ID_GPHOTO2}="1", ENV{GPHOTO2_DRIVER}="proprietary", MODE="0660", GROUP="plugdev"
KERNEL=="sg[0-9]*", ATTRS{idVendor}=="07b4", ATTRS{idProduct}=="0105", ENV{ID_GPHOTO2}="1", ENV{GPHOTO2_DRIVER}="proprietary", MODE="0660", GROUP="plugdev"
KERNEL=="sg[0-9]*", ATTRS{idVendor}=="07b4", ATTRS{idProduct}=="0109", ENV{ID_GPHOTO2}="1", ENV{GPHOTO2_DRIVER}="proprietary", MODE="0660", GROUP="plugdev"
KERNEL=="sg[0-9]*", ATTRS{idVendor}=="07b4", ATTRS{idProduct}=="0105", ENV{ID_GPHOTO2}="1", ENV{GPHOTO2_DRIVER}="proprietary", MODE="0660", GROUP="plugdev"
KERNEL=="sg[0-9]*", ATTRS{idVendor}=="07b4", ATTRS{idProduct}=="0105", ENV{ID_GPHOTO2}="1", ENV{GPHOTO2_DRIVER}="proprietary", MODE="0660", GROUP="plugdev"
KERNEL=="sg[0-9]*", ATTRS{idVendor}=="07b4", ATTRS{idProduct}=="0105", ENV{ID_GPHOTO2}="1", ENV{GPHOTO2_DRIVER}="proprietary", MODE="0660", GROUP="plugdev"
KERNEL=="sg[0-9]*", ATTRS{idVendor}=="07b4", ATTRS{idProduct}=="0105", ENV{ID_GPHOTO2}="1", ENV{GPHOTO2_DRIVER}="proprietary", MODE="0660", GROUP="plugdev"
KERNEL=="sg[0-9]*", ATTRS{idVendor}=="07b4", ATTRS{idProduct}=="0105", ENV{ID_GPHOTO2}="1", ENV{GPHOTO2_DRIVER}="proprietary", MODE="0660", GROUP="plugdev"
KERNEL=="sg[0-9]*", ATTRS{idVendor}=="07b4", ATTRS{idProduct}=="0109", ENV{ID_GPHOTO2}="1", ENV{GPHOTO2_DRIVER}="proprietary", MODE="0660", GROUP="plugdev"
KERNEL=="sg[0-9]*", ATTRS{idVendor}=="07b4", ATTRS{idProduct}=="0109", ENV{ID_GPHOTO2}="1", ENV{GPHOTO2_DRIVER}="proprietary", MODE="0660", GROUP="plugdev"
KERNEL=="sg[0-9]*", ATTRS{idVendor}=="07b4", ATTRS{idProduct}=="0109", ENV{ID_GPHOTO2}="1", ENV{GPHOTO2_DRIVER}="proprietary", MODE="0660", GROUP="plugdev"
KERNEL=="sg[0-9]*", ATTRS{idVendor}=="07b4", ATTRS{idProduct}=="0109", ENV{ID_GPHOTO2}="1", ENV{GPHOTO2_DRIVER}="proprietary", MODE="0660", GROUP="plugdev"
KERNEL=="sg[0-9]*", ATTRS{idVendor}=="25fb", ATTRS{idProduct}=="0130", ENV{ID_GPHOTO2}="1", ENV{GPHOTO2_DRIVER}="proprietary", MODE="0660", GROUP="plugdev"
KERNEL=="sg[0-9]*", ATTRS{idVendor}=="0a17", ATTRS{idProduct}=="0070", ENV{ID_GPHOTO2}="1", ENV{GPHOTO2_DRIVER}="proprietary", MODE="0660", GROUP="plugdev"
KERNEL=="sg[0-9]*", ATTRS{idVendor}=="0a17", ATTRS{idProduct}=="00a1", ENV{ID_GPHOTO2}="1", ENV{GPHOTO2_DRIVER}="proprietary", MODE="0660", GROUP="plugdev"
KERNEL=="sg[0-9]*", ATTRS{idVendor}=="0a17", ATTRS{idProduct}=="006e", ENV{ID_GPHOTO2}="1", ENV{GPHOTO2_DRIVER}="proprietary", MODE="0660", GROUP="plugdev"
KERNEL=="sg[0-9]*", ATTRS{idVendor}=="0a17", ATTRS{idProduct}=="0093", ENV{ID_GPHOTO2}="1", ENV{GPHOTO2_DRIVER}="proprietary", MODE="0660", GROUP="plugdev"
KERNEL=="sg[0-9]*", ATTRS{idVendor}=="0a17", ATTRS{idProduct}=="0091", ENV{ID_GPHOTO2}="1", ENV{GPHOTO2_DRIVER}="proprietary", MODE="0660", GROUP="plugdev"
KERNEL=="sg[0-9]*", ATTRS{idVendor}=="25fb", ATTRS{idProduct}=="0164", ENV{ID_GPHOTO2}="1", ENV{GPHOTO2_DRIVER}="proprietary", MODE="0660", GROUP="plugdev"
KERNEL=="sg[0-9]*", ATTRS{idVendor}=="25fb", ATTRS{idProduct}=="0132", ENV{ID_GPHOTO2}="1", ENV{GPHOTO2_DRIVER}="proprietary", MODE="0660", GROUP="plugdev"
KERNEL=="sg[0-9]*", ATTRS{idVendor}=="25fb", ATTRS{idProduct}=="017a", ENV{ID_GPHOTO2}="1", ENV{GPHOTO2_DRIVER}="proprietary", MODE="0660", GROUP="plugdev"
KERNEL=="sg[0-9]*", ATTRS{idVendor}=="25fb", ATTRS{idProduct}=="0160", ENV{ID_GPHOTO2}="1", ENV{GPHOTO2_DRIVER}="proprietary", MODE="0660", GROUP="plugdev"
KERNEL=="sg[0-9]*", ATTRS{idVendor}=="25fb", ATTRS{idProduct}=="0102", ENV{ID_GPHOTO2}="1", ENV{GPHOTO2_DRIVER}="proprietary", MODE="0660", GROUP="plugdev"
KERNEL=="sg[0-9]*", ATTRS{idVendor}=="25fb", ATTRS{idProduct}=="0148", ENV{ID_GPHOTO2}="1", ENV{GPHOTO2_DRIVER}="proprietary", MODE="0660", GROUP="plugdev"
KERNEL=="sg[0-9]*", ATTRS{idVendor}=="25fb", ATTRS{idProduct}=="014a", ENV{ID_GPHOTO2}="1", ENV{GPHOTO2_DRIVER}="proprietary", MODE="0660", GROUP="plugdev"
KERNEL=="sg[0-9]*", ATTRS{idVendor}=="25fb", ATTRS{idProduct}=="017c", ENV{ID_GPHOTO2}="1", ENV{GPHOTO2_DRIVER}="proprietary", MODE="0660", GROUP="plugdev"
KERNEL=="sg[0-9]*", ATTRS{idVendor}=="0a17", ATTRS{idProduct}=="0009", ENV{ID_GPHOTO2}="1", ENV{GPHOTO2_DRIVER}="proprietary", MODE="0660", GROUP="plugdev"
KERNEL=="sg[0-9]*", ATTRS{idVendor}=="0a17", ATTRS{idProduct}=="0007", ENV{ID_GPHOTO2}="1", ENV{GPHOTO2_DRIVER}="proprietary", MODE="0660", GROUP="plugdev"
KERNEL=="sd[a-z]*", ATTRS{idVendor}=="1403", ATTRS{idProduct}=="0001", ENV{ID_GPHOTO2}="1", ENV{GPHOTO2_DRIVER}="proprietary", MODE="0660", GROUP="plugdev"
KERNEL=="sg[0-9]*", ATTRS{idVendor}=="0168", ATTRS{idProduct}=="3011", ENV{ID_GPHOTO2}="1", ENV{GPHOTO2_DRIVER}="proprietary", MODE="0660", GROUP="plugdev"

LABEL="libgphoto2_rules_end"
```

**Comment by andi34** [comment]
[my-logfile.txt](https://github.com/andreknieriem/photobooth/files/3701804/my-logfile.txt)

**Comment by andi34** [comment]
Add user www-data to plugdev group safe enough?

**Comment by sualko** [comment]
> Add user www-data to plugdev group safe enough?

I think that would be ok. Didn't know that the latest installer creates this list, but that is great.

**Comment by andi34** [comment]
Ok, I'll test to if it fixed the issue

**Comment by andi34** [comment]
https://www.linuxquestions.org/questions/linux-server-73/permissions-problem-with-gphoto2-and-php-844608/

Mh.. a quick search shows this might not be a solution to run it from php

**Comment by andi34** [comment]
```
sudo gpasswd -a www-data plugdev
```
allows to take a picture  via commandline
```
sudo -u www-data gphoto2 --capture-image
```

**Comment by andi34** [comment]
@sualko I'll update instructions here for myself until everything is working https://github.com/andi34/git_and_linux_stuff/blob/master/pi.md

Can play around tomorrow a little bit more, out of time today. Maybe it's enough on current master branch without the need of yarn install & build.

Maybe I should see that it works on current branch with changed permissions before we dig around the issue on refactoring branch?

**Comment by andi34** [comment]
Works fine with https://github.com/sualko/photobooth/pull/4

Should be merged with https://github.com/andreknieriem/photobooth/pull/106

**Comment by andi34** [comment]
Ready to be merged if you merged my PR @sualko

**Pull request merged**
