### PR TITLE
Add option to choose a default image filter

### PR DESCRIPTION
**Pull request by andi34**
- Allow to use a filter for all photos by default.

### CODE REVIEW

**Comment by sualko** [comment]
This will conflict with #135, but I will integrate your changes there and mention you as author. Please leave this open, so that I don't forget it.

**Comment by sualko** [comment]
Thought changing it directly here is nicer. I hope that was ok. Please review and merge.

**Comment by andi34** [comment]
whoops, haven't seen you have updated it. restored your changes.
will test in the evening.

**Comment by andi34** [comment]
Btw. It's always ok to improve existing changes if possible and force-push if needed. That's why we have those different branches until changes are merged.

**Pull request merged**
